config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#show"
  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :edit, :update]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true
  validates :url, :url => true

  belongs_to :user
  def status
    return "read" if read
    "unread"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  validates :email, presence: true, uniqueness: true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::V1::BaseController
  respond_to :json
  def update
    respond_with Link.find(params[:id]).update(link_params)
  end

  private
    def link_params
      params.require(:link).permit(:read)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to login_path unless current_user
  end

  def redirect_logged_in
    redirect_to links_path if current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :redirect_logged_in
  def show
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_user

  def index
    @links = current_user.links
  end

  def create
    @link = Link.new(link_params.merge({user: current_user}))
    if @link.save
      flash[:success] = "Added new link: #{@link.title}"
      redirect_to links_path
    else
      flash[:danger] = "Not valid link submission"
      redirect_to links_path
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      flash[:success] = "Your link was updated!"
      redirect_to links_path
    else
      flash.now[:danger] = "Your link update was invalid!"
      render :edit
    end
  end

  private
    def link_params
      params.require(:link).permit(:title, :url, :read)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      flash[:success] = "You have sucessfully logged in!"
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:danger] = "Invalid Credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have signed up!"
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:danger] = "Invalid account details"
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def change_status_text(status)
    return "Mark as Unread" if status
    "Mark as Read"
  end
end

app/views/dashboard/show.html.haml
%h1 Welcome to Thoughtbox
= link_to "Log in", login_path, class: "btn btn-default"
= link_to "Sign up", new_user_path , class: "btn btn-default"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ThoughtboxEval
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    - if current_user
      %nav.navbar.navbar-default.navbar-fixed-top
        = link_to "Sign Out", logout_path, method: :delete, class:"btn btn-danger navbar-btn navbar-right"
    -flash.each do |name, msg|
      %div{class: "alert alert-#{name}",role: "alert"}
        = "#{msg}"
    .container
      = yield

app/views/links/_link.html.haml
.link{class: "#{link.status}", id: "link-#{link.id}"}
  =link_to link.title, link.url
  %button.btn.btn-default.change-status
    =change_status_text(link.read)
  =link_to "Edit link", edit_link_path(link.id), class: "btn btn-warning"

app/views/links/_link_actions.html.haml
.link-actions
  %button.btn.btn-default#alphabetical Sort alphabetically
  %button.btn.btn-default#read-links Only read links
  %button.btn.btn-default#unread-links Only unread links
  %button.btn.btn-default#all-links All links
  %form{class: "action"}
    %label{for:"link_search"} Search links:
    %input{type:"text", id:"link_search", placeholder: "pandas"}

app/views/links/edit.html.haml
.h1 Edit your link!
.edit-link-form
  =form_for @link do |f|
    = f.label :title
    = f.text_field :title, size: 50
    %br
    = f.label :url
    = f.text_field :url, size: 50
    %br
    = f.submit "Edit link", class: "btn btn-success"

app/views/links/index.html.haml
%h1 Create a sweet new link
.new-link
  =form_for Link.new, url: links_path, method: :post do |f|
    = f.label :title
    = f.text_field :title
    %br
    = f.label :url
    = f.text_field :url
    %br
    = f.submit "Submit new link", class: "btn btn-success"

%h1
  All the links for
  = "#{current_user.email}" if current_user
= render partial: "link_actions"
.links
  = render partial: "link", collection: @links

app/views/users/new.html.haml
%h1 Create a new account!

= form_for @user do |f|
  =f.label :email
  =f.email_field :email
  =f.label :password
  =f.password_field :password
  =f.label :password_confirmation
  =f.password_field :password_confirmation
  =f.submit "Create account", class: "btn btn-success"